config/routes.rb
Rails.application.routes.draw do
  # Public 
  root "main#index"
  get '/posts', to: 'posts#index'
  
  # API
  post '/posts/api', to: 'posts#api_new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forum_message.rb
class ForumMessage < ApplicationRecord
  validates :author, presence: true, length: {minimum: 2}
  validates :text, presence: true, length: {minimum: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Public
  def index
    @forum_messages = ForumMessage.all
  end

  # API
  def api_new
    # todo: use model in form?
    @forum_message = ForumMessage.new get_forum_message(params)
    if @forum_message.save
    else
      # todo: add session error message
    end
    redirect_to posts_path
  end
  
  private
  
  def get_forum_message(params)
    params.permit(:author, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsForum</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="header-logo"><%= link_to "Типа ФОРУМ", root_url %></div>
      <div class="header-logo"><%= link_to "Посты", posts_path %></div>
      <div class="mid-v">
        <div class="header-state">Состояние</div>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <div class="copyright mid-v">Сделано Alex Krol 2022 &#169; <krolmail@list.ru></div>
    </footer>
  </body>
</html>

app/views/main/index.html.erb
Главная страница

app/views/posts/index.html.erb
<ul class="themes-list">
  <% @forum_messages.each do |message| %>
  <li class="themes-item">
    <div class="theme-author"><%= message.author %></div>
    <div class="last-post"><%= message.text %></div>
    <div class="theme-buttons">
      <button>Редактировать</button>
      <button>Удалить</button>
    </div>
  </li>
  <% end %>
</ul>
<%= form_with url: posts_api_path, html: {class: "new-post"} do |f| %>
  <%= f.text_field :author, required: true, minlength: 2, placeholder: "Имя Автора" %>
  <%= f.text_area :text, rows: 10, required: true, minlength: 2, placeholder: "Ваш текст..." %>
  <%= f.submit "Опубликовать пост", class: "button" %>
<% end %>